git rm configs/hcp/daformer.py
git rm configs/hcp/daformer_colormix_source.py
git rm configs/hcp/daformer_mic.py
git rm configs/hcp/daformer_mic_colormix_source.py
git rm configs/hcp/daformerconv.py
git rm configs/hcp/daformerconv_colormix.py
git rm configs/hcp/danet.py
git rm configs/hcp/danet_colormix.py
git rm configs/hcp/deeplabv2.py
git rm configs/hcp/deeplabv2_colormix.py
git rm configs/hcp/deeplabv2red.py
git rm configs/hcp/deeplabv2red_colormix.py
git rm configs/hcp/segformer_colormix_3.py
git rm configs/hcp/segformer_colormix_4.py
git rm configs/hcp/segformer_colormix_5.py
git rm configs/hcp/segformer_colormix_6.py
git rm configs/hcp/segformer_colormix_v2.py
git rm configs/hcp/segformer_mic_colormix_source.py
git rm configs/spine/segformer_colormix_3.py
git rm configs/spine/segformer_colormix_4.py
git rm configs/spine/segformer_colormix_5.py
git rm configs/wmh/segformer_colormix_2.py
git rm configs/wmh/segformer_colormix_3.py
git rm configs/wmh/segformer_colormix_4.py